version: '3.4'

services:
  mongo:
    image: mongo:5.0.3
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"

volumes:
  dbdata:
